name: newprojectfirebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # App icons
  flutter_launcher_icons: ^0.13.1

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4

  # Google Sign-In
  google_sign_in: ^6.2.1

  # State management
  provider: ^6.1.5+1



  # Timezone for scheduling notifications (working version)
  timezone: ^0.9.4

  #flutter notifications
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.2.1
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  dio: ^5.9.0
  cloud_firestore: ^6.1.1
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/yatra.png"
  min_sdk_android: 29

flutter:
  uses-material-design: true

  assets:
    - assets/
